prefix = "."
stop-words = "stopwords.txt"

dataset = "reviews"
corpus = "line.toml"
index = "idx"


[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[[analyzers]]
method = "ngram-word"
ngram = 2
filter = "default-chain"

